import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

/**
 * `next lint` shipped as an interactive setup wizard because no config
 * existed — anyone cloning this repo and running `npm run lint` got a
 * prompt instead of a lint run.
 */
const config = [
  /* next-env.d.ts is generated by Next on every build and is gitignored;
     linting a file we do not author or control is noise. */
  { ignores: [".next/**", "node_modules/**", "out/**", "next-env.d.ts"] },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
